//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""66860b0f-d7d1-438c-9f00-ceb79274806a"",
            ""actions"": [
                {
                    ""name"": ""StarboardOar"",
                    ""type"": ""Value"",
                    ""id"": ""65863f7e-8a33-4aed-9c30-fed2777106f9"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PortOar"",
                    ""type"": ""Value"",
                    ""id"": ""787c145c-ab2d-4c4f-bcff-6dc39cf6fe7d"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GrabOars"",
                    ""type"": ""Button"",
                    ""id"": ""02006ea7-687e-47d1-b007-f2c5189ad200"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LiftPortOar"",
                    ""type"": ""Button"",
                    ""id"": ""b7168b8d-3db2-46e8-ab0f-25c57224c425"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LiftStarboardOar"",
                    ""type"": ""Value"",
                    ""id"": ""048f8ad9-4dac-4891-8b22-ad5f9922e9ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryContact"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9d455996-3258-40fa-9524-e2c3a4215cb5"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPosition"",
                    ""type"": ""Value"",
                    ""id"": ""184c34e7-7edc-462f-899a-74a90114609b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryPosition"",
                    ""type"": ""Value"",
                    ""id"": ""06db094e-77ae-4323-9813-b0c18d646b6d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerMotion"",
                    ""type"": ""Value"",
                    ""id"": ""2d8f0928-db5b-4271-af2c-594105bb3d53"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraMotion"",
                    ""type"": ""Value"",
                    ""id"": ""8fb7b240-c5ae-4b4e-a194-b7422c11701b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d8d66a3e-5f96-4596-b743-9c155441fe33"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StarboardOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8500c88d-01f5-4ce3-b5df-4eea9cb1f1dc"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StarboardOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Analog"",
                    ""id"": ""0cc6ff40-52b0-4927-9b14-5be506a2102e"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortOar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a981e0e8-d29b-42a3-94af-0425c79ed48c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a679dc7f-3149-40f0-a0b5-6a602f844ed9"",
                    ""path"": ""<Joystick>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dfff3372-0164-4a19-af20-818d875f0b70"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""33f09680-f59b-48c1-92f1-e767ce9c2538"",
                    ""path"": ""<Joystick>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""05fb7102-9536-494f-bc5a-8921c5a184f8"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b64f388-65e2-47f8-ad25-90492bf62940"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabOars"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f19a929b-cc9d-4388-a1cf-4cb29f979c11"",
                    ""path"": ""<HID::Logitech Logitech Dual Action>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabOars"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b75c2b0-195b-4162-9a12-7247e4676109"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LiftPortOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a58faee-39ee-4100-9b00-978df3270033"",
                    ""path"": ""<HID::Logitech Logitech Dual Action>/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LiftPortOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""362b61cf-95f3-454d-ad81-d79292c84daa"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LiftStarboardOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e850da39-f2fc-4844-bda3-599cdddd5bb7"",
                    ""path"": ""<HID::Logitech Logitech Dual Action>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LiftStarboardOar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea355500-0466-4655-ad43-f0c14cd3b6ce"",
                    ""path"": ""<Touchscreen>/touch0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e804a4c6-efa6-4482-94d7-28cd23681643"",
                    ""path"": ""<Touchscreen>/touch0/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""054121d7-dca9-4cf7-9105-4daa250d7049"",
                    ""path"": ""<Touchscreen>/touch1/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbe2e54d-98a4-49bf-8461-14bbcf0903b1"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b52f7d8b-78c8-4614-b039-84bd2335f5ab"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_StarboardOar = m_Gameplay.FindAction("StarboardOar", throwIfNotFound: true);
        m_Gameplay_PortOar = m_Gameplay.FindAction("PortOar", throwIfNotFound: true);
        m_Gameplay_GrabOars = m_Gameplay.FindAction("GrabOars", throwIfNotFound: true);
        m_Gameplay_LiftPortOar = m_Gameplay.FindAction("LiftPortOar", throwIfNotFound: true);
        m_Gameplay_LiftStarboardOar = m_Gameplay.FindAction("LiftStarboardOar", throwIfNotFound: true);
        m_Gameplay_PrimaryContact = m_Gameplay.FindAction("PrimaryContact", throwIfNotFound: true);
        m_Gameplay_PrimaryPosition = m_Gameplay.FindAction("PrimaryPosition", throwIfNotFound: true);
        m_Gameplay_SecondaryPosition = m_Gameplay.FindAction("SecondaryPosition", throwIfNotFound: true);
        m_Gameplay_PlayerMotion = m_Gameplay.FindAction("PlayerMotion", throwIfNotFound: true);
        m_Gameplay_CameraMotion = m_Gameplay.FindAction("CameraMotion", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_StarboardOar;
    private readonly InputAction m_Gameplay_PortOar;
    private readonly InputAction m_Gameplay_GrabOars;
    private readonly InputAction m_Gameplay_LiftPortOar;
    private readonly InputAction m_Gameplay_LiftStarboardOar;
    private readonly InputAction m_Gameplay_PrimaryContact;
    private readonly InputAction m_Gameplay_PrimaryPosition;
    private readonly InputAction m_Gameplay_SecondaryPosition;
    private readonly InputAction m_Gameplay_PlayerMotion;
    private readonly InputAction m_Gameplay_CameraMotion;
    public struct GameplayActions
    {
        private @PlayerControls m_Wrapper;
        public GameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @StarboardOar => m_Wrapper.m_Gameplay_StarboardOar;
        public InputAction @PortOar => m_Wrapper.m_Gameplay_PortOar;
        public InputAction @GrabOars => m_Wrapper.m_Gameplay_GrabOars;
        public InputAction @LiftPortOar => m_Wrapper.m_Gameplay_LiftPortOar;
        public InputAction @LiftStarboardOar => m_Wrapper.m_Gameplay_LiftStarboardOar;
        public InputAction @PrimaryContact => m_Wrapper.m_Gameplay_PrimaryContact;
        public InputAction @PrimaryPosition => m_Wrapper.m_Gameplay_PrimaryPosition;
        public InputAction @SecondaryPosition => m_Wrapper.m_Gameplay_SecondaryPosition;
        public InputAction @PlayerMotion => m_Wrapper.m_Gameplay_PlayerMotion;
        public InputAction @CameraMotion => m_Wrapper.m_Gameplay_CameraMotion;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @StarboardOar.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnStarboardOar;
                @StarboardOar.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnStarboardOar;
                @StarboardOar.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnStarboardOar;
                @PortOar.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPortOar;
                @PortOar.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPortOar;
                @PortOar.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPortOar;
                @GrabOars.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnGrabOars;
                @GrabOars.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnGrabOars;
                @GrabOars.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnGrabOars;
                @LiftPortOar.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLiftPortOar;
                @LiftPortOar.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLiftPortOar;
                @LiftPortOar.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLiftPortOar;
                @LiftStarboardOar.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLiftStarboardOar;
                @LiftStarboardOar.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLiftStarboardOar;
                @LiftStarboardOar.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLiftStarboardOar;
                @PrimaryContact.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimaryContact;
                @PrimaryContact.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimaryContact;
                @PrimaryContact.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimaryContact;
                @PrimaryPosition.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimaryPosition;
                @PrimaryPosition.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimaryPosition;
                @PrimaryPosition.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimaryPosition;
                @SecondaryPosition.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondaryPosition;
                @SecondaryPosition.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondaryPosition;
                @SecondaryPosition.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondaryPosition;
                @PlayerMotion.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlayerMotion;
                @PlayerMotion.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlayerMotion;
                @PlayerMotion.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPlayerMotion;
                @CameraMotion.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCameraMotion;
                @CameraMotion.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCameraMotion;
                @CameraMotion.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCameraMotion;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @StarboardOar.started += instance.OnStarboardOar;
                @StarboardOar.performed += instance.OnStarboardOar;
                @StarboardOar.canceled += instance.OnStarboardOar;
                @PortOar.started += instance.OnPortOar;
                @PortOar.performed += instance.OnPortOar;
                @PortOar.canceled += instance.OnPortOar;
                @GrabOars.started += instance.OnGrabOars;
                @GrabOars.performed += instance.OnGrabOars;
                @GrabOars.canceled += instance.OnGrabOars;
                @LiftPortOar.started += instance.OnLiftPortOar;
                @LiftPortOar.performed += instance.OnLiftPortOar;
                @LiftPortOar.canceled += instance.OnLiftPortOar;
                @LiftStarboardOar.started += instance.OnLiftStarboardOar;
                @LiftStarboardOar.performed += instance.OnLiftStarboardOar;
                @LiftStarboardOar.canceled += instance.OnLiftStarboardOar;
                @PrimaryContact.started += instance.OnPrimaryContact;
                @PrimaryContact.performed += instance.OnPrimaryContact;
                @PrimaryContact.canceled += instance.OnPrimaryContact;
                @PrimaryPosition.started += instance.OnPrimaryPosition;
                @PrimaryPosition.performed += instance.OnPrimaryPosition;
                @PrimaryPosition.canceled += instance.OnPrimaryPosition;
                @SecondaryPosition.started += instance.OnSecondaryPosition;
                @SecondaryPosition.performed += instance.OnSecondaryPosition;
                @SecondaryPosition.canceled += instance.OnSecondaryPosition;
                @PlayerMotion.started += instance.OnPlayerMotion;
                @PlayerMotion.performed += instance.OnPlayerMotion;
                @PlayerMotion.canceled += instance.OnPlayerMotion;
                @CameraMotion.started += instance.OnCameraMotion;
                @CameraMotion.performed += instance.OnCameraMotion;
                @CameraMotion.canceled += instance.OnCameraMotion;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnStarboardOar(InputAction.CallbackContext context);
        void OnPortOar(InputAction.CallbackContext context);
        void OnGrabOars(InputAction.CallbackContext context);
        void OnLiftPortOar(InputAction.CallbackContext context);
        void OnLiftStarboardOar(InputAction.CallbackContext context);
        void OnPrimaryContact(InputAction.CallbackContext context);
        void OnPrimaryPosition(InputAction.CallbackContext context);
        void OnSecondaryPosition(InputAction.CallbackContext context);
        void OnPlayerMotion(InputAction.CallbackContext context);
        void OnCameraMotion(InputAction.CallbackContext context);
    }
}
